services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./docker-data-2/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example
      - POSTGRES_DB=dev
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 1488:80
    volumes:
      - ./docker-data-2/pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.ru
      - PGADMIN_DEFAULT_PASSWORD=example
      - PGADMIN_DEFAUIL_USER=example